global:
  resolve_timeout: 5m
route:
  receiver: 'telegram'
receivers:
- name: 'telegram'
  webhook_configs:
  - send_resolved: true
    url: 'http://203.162.121.72:8080'
templates:
  - 'alert_templates/default.tmpl'
